In [2]:
!pip install numpy --upgrade

  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.0
    Uninstalling numpy-1.19.0:
      Successfully uninstalled numpy-1.19.0


You should consider upgrading via the 'c:\users\nikita.thakur\appdata\local\programs\python\python36\python.exe -m pip install --upgrade pip' command.


In [3]:
!pip install --upgrade pip

  Attempting uninstall: pip
    Found existing installation: pip 20.1.1
    Uninstalling pip-20.1.1:
      Successfully uninstalled pip-20.1.1


ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\NIKITA~1.THA\\AppData\\Local\\Temp\\pip-uninstall-yvnyqv_q\\pip.exe'
Consider using the `--user` option or check the permissions.



In [4]:
import numpy as np

In [5]:
Array_One = np.array([0,1,3,5,7,9])
Array_One

array([0, 1, 3, 5, 7, 9])

In [8]:
array_of_zeros = np.zeros((2,3))
array_of_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
array_of_ones = np.ones((3,2))
array_of_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
array_of_ones = np.ones((3,2), dtype = np.int32)
array_of_ones

array([[1, 1],
       [1, 1],
       [1, 1]])

In [12]:
array_empty = np.empty((3,2))
array_empty

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
array_eye = np.eye(4)
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
array_of_evens = np.arange(2,24,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [16]:
array_of_floats = np.arange(1,3,0.3)
array_of_floats

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8])

In [20]:
array_2D = np.array([(2,3,4),(5,6,7)])
array_2D

array([[2, 3, 4],
       [5, 6, 7]])

In [21]:
array_2D.shape

(2, 3)

In [22]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [23]:
array_nd = np.arange(8).reshape(2,4)
array_nd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
array_nd = np.arange(6).reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [25]:
array_ones = np.ones_like(array_nd)
array_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])