In [1]:
import numpy as np

In [3]:
p = np.array([9,8,7])
q = np.array([3,2,4])

In [4]:
p + q

array([12, 10, 11])

In [5]:
p - q

array([6, 6, 3])

In [7]:
print(p*q)
print(p/q)
print(p%q)

[27 16 28]
[3.   4.   1.75]
[0 0 3]


In [8]:
p%2

array([1, 0, 1], dtype=int32)

In [9]:
p > 8

array([ True, False, False])

In [10]:
p<9

array([False,  True,  True])

In [12]:
p.dot(q)

71

In [13]:
np.dot(p,q)

71

In [14]:
p *= 4

In [15]:
p

array([36, 32, 28])

In [16]:
fleet_mileage = np.array([23333,346334,45656,233332,959964])

In [17]:
fleet_mileage.sum()

1608619

In [18]:
fleet_mileage.min()

23333

In [19]:
fleet_mileage.max()

959964

In [20]:
fleet_mileage.mean()

321723.8

In [24]:
num_2d = np.arange(16).reshape(4,4)
num_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
num_2d.sum()

120

In [26]:
num_2d.sum(axis = 0)

array([24, 28, 32, 36])

In [27]:
num_2d.sum(axis = 1)

array([ 6, 22, 38, 54])

In [28]:
num_2d.min(axis = 1)

array([ 0,  4,  8, 12])

In [29]:
num_2d.mean(axis = 1)

array([ 1.5,  5.5,  9.5, 13.5])