In [1]:
import numpy as np

In [2]:
x = np.array([2,4,6,8,20])
y = np.array([5,5,5,5,5])

In [3]:
x*y

array([ 10,  20,  30,  40, 100])

In [4]:
z = 10

In [5]:
x*z

array([ 20,  40,  60,  80, 200])

In [7]:
ones = np.ones((3,4))

In [8]:
ones*z

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])