In [1]:
import numpy as np

In [3]:
x = np.arange(10)**3
x

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [4]:
x[3]

27

In [5]:
x[-4]

216

In [6]:
x[1:8]

array([  1,   8,  27,  64, 125, 216, 343], dtype=int32)

In [7]:
x[3:-3]

array([ 27,  64, 125, 216], dtype=int32)

In [8]:
x[:]

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [9]:
x[:10:2]

array([  0,   8,  64, 216, 512], dtype=int32)

In [10]:
x[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

In [11]:
x[...]

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)