In [1]:
import numpy as np
import csv

In [2]:
x = np.arange(14)**2
x

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169], dtype=int32)

In [3]:
x[3], x[7],x[9], x[13]

(9, 49, 81, 169)

In [4]:
mask1 = [3,7,9,13]
x[mask1]

array([  9,  49,  81, 169], dtype=int32)

In [5]:
x[[3,8,9,13]]

array([  9,  64,  81, 169], dtype=int32)

In [7]:
mask2 = np.array([[3,5],[2,8]])
mask2

array([[3, 5],
       [2, 8]])

In [8]:
x[mask2]

array([[ 9, 25],
       [ 4, 64]], dtype=int32)

In [9]:
x[mask1]

array([  9,  49,  81, 169], dtype=int32)

In [10]:
x[mask1] = 999

In [11]:
x

array([  0,   1,   4, 999,  16,  25,  36, 999,  64, 999, 100, 121, 144,
       999], dtype=int32)