In [1]:
import numpy as np

In [2]:
x = np.arange(25).reshape(5,5)

In [3]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [6]:
for data in x.flatten(order = 'F'):
    print(data)

0
5
10
15
20
1
6
11
16
21
2
7
12
17
22
3
8
13
18
23
4
9
14
19
24


In [7]:
for i in np.nditer(x):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [8]:
for i in np.nditer(x, order = 'f'):
    print(i)

0
5
10
15
20
1
6
11
16
21
2
7
12
17
22
3
8
13
18
23
4
9
14
19
24


In [9]:
for i in np.nditer(x, order = 'F', flags = ['external_loop']):
    print(i)

[ 0  5 10 15 20]
[ 1  6 11 16 21]
[ 2  7 12 17 22]
[ 3  8 13 18 23]
[ 4  9 14 19 24]


In [10]:
for i in np.nditer(x):
    x[...] = x*x

In [11]:
x

array([[          0,           1,           0,  -402653183,           0],
       [ -134217727,           0, -1342177279,           0,  -805306367],
       [          0,  1476395009,           0, -2013265919,           0],
       [ -536870911,           0,   536870913,           0,  1207959553],
       [          0, -1744830463,           0, -1879048191,           0]])