In [1]:
import numpy as np

In [2]:
x = np.arange(8)

In [3]:
print(x)

[0 1 2 3 4 5 6 7]


In [4]:
y = np.arange(16).reshape(4,4)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [6]:
y = np.arange(36).reshape(3,4,3)
print(y)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [7]:
np.arange(120303)

array([     0,      1,      2, ..., 120300, 120301, 120302])

In [9]:
np.arange(12100).reshape(110,110)

array([[    0,     1,     2, ...,   107,   108,   109],
       [  110,   111,   112, ...,   217,   218,   219],
       [  220,   221,   222, ...,   327,   328,   329],
       ...,
       [11770, 11771, 11772, ..., 11877, 11878, 11879],
       [11880, 11881, 11882, ..., 11987, 11988, 11989],
       [11990, 11991, 11992, ..., 12097, 12098, 12099]])

In [11]:
np.set_printoptions(threshold = np.nan)

ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation

In [12]:
print(np.arange(100).reshape(10,10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [13]:
np.set_printoptions(threshold = 50)
print(np.arange(100).reshape(10,10))

[[ 0  1  2 ...  7  8  9]
 [10 11 12 ... 17 18 19]
 [20 21 22 ... 27 28 29]
 ...
 [70 71 72 ... 77 78 79]
 [80 81 82 ... 87 88 89]
 [90 91 92 ... 97 98 99]]
