In [1]:
import numpy as np

In [2]:
p = np.arange(12)
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
print('split the array to produce 4 equal sized sub arrays')
np.split(p,4)

split the array to produce 4 equal sized sub arrays


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [4]:
np.split(p,5)

ValueError: array split does not result in an equal division

In [5]:
np.split(p,[3,8])

[array([0, 1, 2]), array([3, 4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [6]:
q = np.arange(16).reshape(2,8)
q

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [8]:
x1,x2 = np.split(q,2)
print(x1)
print(x2)

[[0 1 2 3 4 5 6 7]]
[[ 8  9 10 11 12 13 14 15]]


In [9]:
x1,x2 = np.hsplit(q,2)
print(x1)
print(x2)

[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [12 13 14 15]]


In [10]:
np.hsplit(q,6)

ValueError: array split does not result in an equal division

In [11]:
np.hsplit(q,3)

ValueError: array split does not result in an equal division

In [12]:
np.hsplit(q,8)

[array([[0],
        [8]]),
 array([[1],
        [9]]),
 array([[ 2],
        [10]]),
 array([[ 3],
        [11]]),
 array([[ 4],
        [12]]),
 array([[ 5],
        [13]]),
 array([[ 6],
        [14]]),
 array([[ 7],
        [15]])]

In [13]:
    np.vsplit(q,2)

[array([[0, 1, 2, 3, 4, 5, 6, 7]]), array([[ 8,  9, 10, 11, 12, 13, 14, 15]])]

In [14]:
    np.vsplit(q,8)

ValueError: array split does not result in an equal division