In [1]:
import numpy as np

In [2]:
circle_radii = np.array([5,10,15,20,25,54])

In [3]:
circle_diameters = circle_radii *2
circle_diameters

array([ 10,  20,  30,  40,  50, 108])

In [4]:
circle_areas = np.pi * circle_radii**2
circle_areas

array([  78.53981634,  314.15926536,  706.85834706, 1256.63706144,
       1963.49540849, 9160.88417787])

In [5]:
np.sin(100/180)
#value needs to be in radians

0.5274153857718655

In [7]:
np.cos(100/180)

0.8496075628495278

In [6]:
np.tan(100/180)

0.6207752953645435

In [8]:
np.arcsin(0.5274153857718655)*180

100.0

In [10]:
x = np.arange(4,31,5)
x

array([ 4,  9, 14, 19, 24, 29])

In [11]:
expo = np.exp(x)
expo

array([5.45981500e+01, 8.10308393e+03, 1.20260428e+06, 1.78482301e+08,
       2.64891221e+10, 3.93133430e+12])

In [12]:
sqrt = np.sqrt(x)
sqrt

array([2.        , 3.        , 3.74165739, 4.35889894, 4.89897949,
       5.38516481])

In [13]:
np.median(x)

16.5

In [15]:
values = np.genfromtxt('dataset1.txt',delimiter=',')

In [16]:
values

array([8.38635041e+08, 8.38637977e+08, 8.38637094e+08, 8.38635044e+08,
       8.38635040e+08, 8.38637095e+08, 8.38637978e+08, 8.38637097e+08,
       8.38635045e+08, 8.38637099e+08, 8.38637979e+08, 8.38635047e+08])

In [19]:
print("Mean = %i" %np.mean(values))
print("Median = %i" %np.median(values))
print("Variance = %i" %np.var(values))
print("Standard Deviation = %i" %np.std(values))

Mean = 838636461
Median = 838637094
Variance = 1547169
Standard Deviation = 1243
